let dados = [
    {
        candidato: "DOUGLAS MELO",
        partido:"PSD - Candidato a Prefeito",
        numero:"55",
        situacao:"Concorrendo",
        tags:" prefeito 55 psd douglas",
    },
    {
        candidato: "JUNIOR SOUSA",
        partido:"PRD - Candidato a Prefeito",
        numero:"25",
        situacao:"Concorrendo",
        tags:"prefeito 25 psd junior",
    },
    {
        candidato: "JUNINHO SINONÔ",
        partido:"NOVO - Candidato a Prefeito",
        numero:"30",
        situacao:"Concorrendo",
        tags:"prefeito 30 novo juninho",
    },
    {
        candidato: "DOUTOR JAMILTON SANTOS",
        partido:"PT - Candidato a Prefeito",
        numero:"13",
        situacao:"Concorrendo",
        tags:"prefeito 13 pt doutor",
    },
    {
        candidato: "ADAILTON COSTA",
        partido:"REDE",
        numero:" 18280",
        situacao:"Concorrendo",
        tags:"vereador",
    },
    {
    candidato: "ADELMO TAVARES",
    partido: "PP",
    numero: "11123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ADEMAR NÔ",
    partido: "CIDADANIA",
    numero: "23666",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ADRIANA MATEUS",
    partido: "REDE",
    numero: "18400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ADRIANO CABELINHO",
    partido: "PV",
    numero: "43213",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "AGUINALDO DA LOBATO",
    partido: "AVANTE",
    numero: "70400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "AILTON JUNIOR",
    partido: "CIDADANIA",
    numero: "23800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALBER ENFERMEIRO",
    partido: "MOBILIZA",
    numero: "33192",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALBERTO DO BARREIRO",
    partido: "REDE",
    numero: "18500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALCIONE PEDAGOGA",
    partido: "PP",
    numero: "11011",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEF BARBEIRO",
    partido: "REDE",
    numero: "18181",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALESSANDRA MORENO",
    partido: "PC do B",
    numero: "65333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEX DE CASTRO",
    partido: "AGIR",
    numero: "36500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEX JESUS",
    partido: "REDE",
    numero: "18190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEX MENESES",
    partido: "SOLIDARIEDADE",
    numero: "77999",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEX PAULO",
    partido: "PODE",
    numero: "20190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEX ROBERTO",
    partido: "UNIÃO",
    numero: "44044",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEXANDRE JAMÓIA",
    partido: "SOLIDARIEDADE",
    numero: "77900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALEXANDRE TOLEDO",
    partido: "PRD",
    numero: "25456",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ALOIZ MARINHO LÓLÓ",
    partido: "AVANTE",
    numero: "70888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANA PAULA DE LELECO",
    partido: "PL",
    numero: "22800",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "ANA RODRIGUES",
    partido: "AVANTE",
    numero: "70456",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANA VASCONCELOS",
    partido: "UNIÃO",
    numero: "44029",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANDRÉ FAZENDA VELHA",
    partido: "NOVO",
    numero: "30800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANDRÉ LONGO",
    partido: "CIDADANIA",
    numero: "23123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANDREA OLIVEIRA",
    partido: "AVANTE",
    numero: "70600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANDREA REIS ENFERMEIRA",
    partido: "PSB",
    numero: "40775",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ÂNGELA RIBEIRO",
    partido: "PSB",
    numero: "40777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANGÉLICA FREITAS",
    partido: "NOVO",
    numero: "30777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ANNA GABRIELLE",
    partido: "SOLIDARIEDADE",
    numero: "77135",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ARLEY ALVES",
    partido: "REPUBLICANOS",
    numero: "10707",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "AUBREY LOCUTOR",
    partido: "PL",
    numero: "22022",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BARBARA ANDRESSA",
    partido: "REPUBLICANOS",
    numero: "10777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BÁRBARA DIAS DA RÁDIO",
    partido: "REDE",
    numero: "18333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BAÚ MOTORISTA DE APP",
    partido: "MOBILIZA",
    numero: "33540",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BEATRIZ VELOSO",
    partido: "PDT",
    numero: "12400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BERNADO VASSOUREIRO",
    partido: "PSB",
    numero: "40059",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BETÃO DO GÁS",
    partido: "AVANTE",
    numero: "70125",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BETINHA DO SÃO GERALDO",
    partido: "SOLIDARIEDADE",
    numero: "77600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BETO DO AÇOUGUE",
    partido: "PSB",
    numero: "40013",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BIA NOGUEIRA CABELEIREIRA",
    partido: "PSB",
    numero: "40567",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BREJEIRO",
    partido: "CIDADANIA",
    numero: "23515",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BRUNA DO ALCUNHA",
    partido: "PT",
    numero: "13333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BRUNÃO MOTOBOY",
    partido: "MDB",
    numero: "15800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BRUNO DA ACADEMIA",
    partido: "PP",
    numero: "11111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "BURRINHO MECÂNICO",
    partido: "PL",
    numero: "22003",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CAIO VALACE",
    partido: "PDT",
    numero: "12123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CAMILA BRAGA ENFERMEIRA",
    partido: "REPUBLICANOS",
    numero: "10010",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CANDINHO NINJA DO BARREIRO",
    partido: "AVANTE",
    numero: "70300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CARLITO APARECIDO PEREIRA",
    partido: "PP",
    numero: "11500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CARLOS PICA PAU",
    partido: "PT",
    numero: "13003",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CARMOSINA MAIA",
    partido: "PT",
    numero: "13300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CASSIA LIMA",
    partido: "UNIÃO",
    numero: "44133",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CESAR MACIEL",
    partido: "PDT",
    numero: "12321",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CHARBEL CASARINO",
    partido: "AVANTE",
    numero: "70500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CHRISTIAN RENNER",
    partido: "PL",
    numero: "22123",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "CIBELE TEIXEIRA",
    partido: "PT",
    numero: "13355",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CINESIO ROCHA",
    partido: "PT",
    numero: "13031",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CINTIA RENATA",
    partido: "AGIR",
    numero: "36123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAÚDIA DA CRECHE",
    partido: "PL",
    numero: "22444",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAUDINEI DIAS",
    partido: "PT",
    numero: "13250",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAUDINHO DO INTERLAGOS",
    partido: "REPUBLICANOS",
    numero: "10433",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAUDINHO POLICIAL",
    partido: "AVANTE",
    numero: "70190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAUDIO ANDRADE",
    partido: "AGIR",
    numero: "36777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAUDIO CARAMELO",
    partido: "REDE",
    numero: "18123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAÚDIO DIM",
    partido: "PL",
    numero: "22345",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "CLAUDIO DO POVO",
    partido: "AGIR",
    numero: "36400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLAYTON GORDIM DA FEIRA",
    partido: "AVANTE",
    numero: "70666",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CLEMENTE PEDRO",
    partido: "NOVO",
    numero: "30888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CONGONHAS",
    partido: "CIDADANIA",
    numero: "23789",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CRISTIANE",
    partido: "PP",
    numero: "11800",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "CRISTIANO MORAIS",
    partido: "MDB",
    numero: "15000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CRISTINA CAMPELO",
    partido: "UNIÃO",
    numero: "44100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CRISTINA DA SAÚDE",
    partido: "SOLIDARIEDADE",
    numero: "77271",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "CRISTINA DO HOSPITAL",
    partido: "PSB",
    numero: "40100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DALTINHO",
    partido: "MOBILIZA",
    numero: "33300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DANIEL SALVADOR",
    partido: "REPUBLICANOS",
    numero: "10333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DARIO SANTANA ORADOR ESPIRITA",
    partido: "PDT",
    numero: "12700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DAVID FERNANDES",
    partido: "PRD",
    numero: "25153",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DAYSE MORGANI",
    partido: "REPUBLICANOS",
    numero: "10618",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DEBORA GONÇALVES",
    partido: "PRD",
    numero: "25779",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DELEGADA STEFÂNIA",
    partido: "PRD",
    numero: "25180",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DENIS ALVES",
    partido: "PDT",
    numero: "12444",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DENISE DO BELO VALE",
    partido: "MDB",
    numero: "15019",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DENISE HEBACH",
    partido: "AVANTE",
    numero: "70000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DEYVISON DA ACOLHER SAÚDE",
    partido: "SOLIDARIEDADE",
    numero: "77100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DIEGO ROSA",
    partido: "NOVO",
    numero: "30003",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DINIZ DESENHOS",
    partido: "REDE",
    numero: "18900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DIONES IRMÃO DO PADRE DÉCIO",
    partido: "PODE",
    numero: "20700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DITA COUTINHO",
    partido: "PDT",
    numero: "12333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DIVALDO CAPUCHINHO",
    partido: "PODE",
    numero: "20999",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DONISETE RIBEIRO",
    partido: "CIDADANIA",
    numero: "23456",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DOUGLAS SAPÃO",
    partido: "CIDADANIA",
    numero: "23007",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "DR MARCELO ROCHA",
    partido: "NOVO",
    numero: "30200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EDIMAR RIBEIRO",
    partido: "PL",
    numero: "22200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EDUARDO NEGÃO",
    partido: "AVANTE",
    numero: "70345",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EGLEIDYS DE OLIVEIRA PARDIM",
    partido: "NOVO",
    numero: "30555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELIEL FERRUGEM",
    partido: "CIDADANIA",
    numero: "23333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELIETH LUCIANO",
    partido: "PODE",
    numero: "20015",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELIS DA ASSOC DAS MULHERLHERES",
    partido: "MOBILIZA",
    numero: "33180",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELMA DA LOJA",
    partido: "CIDADANIA",
    numero: "23024",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELTON LACERDA",
    partido: "PRD",
    numero: "25000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ELZA DO RESTAURANTE",
    partido: "REPUBLICANOS",
    numero: "10111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ERALDO DA SAÚDE",
    partido: "PSB",
    numero: "40000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EREXA",
    partido: "MOBILIZA",
    numero: "33400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EUCLIDES DA FARMACIA LOBATO",
    partido: "PDT",
    numero: "12000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "EVANIO DE OLIVEIRA",
    partido: "PP",
    numero: "11457",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FABIANA CHICA DO AÇOUGUE",
    partido: "SOLIDARIEDADE",
    numero: "77333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FABIO PAIVA",
    partido: "PDT",
    numero: "12420",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "FABÍOLA MENDES",
    partido: "AGIR",
    numero: "36900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FABRICIO NASCIMENTO",
    partido: "MOBILIZA",
    numero: "33700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FERNANDA DO SINDICATO",
    partido: "PT",
    numero: "13123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FERNANDA SOUZA",
    partido: "PRD",
    numero: "25015",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FERNANDO CALDEIRA",
    partido: "NOVO",
    numero: "30030",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FERNANDO SANTOS",
    partido: "REPUBLICANOS",
    numero: "10153",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FLÁVIA PATRÍCIA PROTETORA",
    partido: "CIDADANIA",
    numero: "23300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FRED DA PIZZA",
    partido: "REPUBLICANOS",
    numero: "10800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "FUSQUINHA DAS CAVALGADAS",
    partido: "PP",
    numero: "11222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GABI DO ALVORADA",
    partido: "AVANTE",
    numero: "70100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GABRIELA SOUZA",
    partido: "UNIÃO",
    numero: "44444",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GARDEL AGUIAR",
    partido: "PRD",
    numero: "25025",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GEISSE ROCHA",
    partido: "PODE",
    numero: "20777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GELSON SILVA",
    partido: "REPUBLICANOS",
    numero: "10121",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GENTIL BOMBEIRO",
    partido: "PDT",
    numero: "12223",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GEORGE MACHADO",
    partido: "PSB",
    numero: "40004",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GERALDINHO CALDO DA LUA",
    partido: "REDE",
    numero: "18000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GERALDINHO DO TRANSPORTE",
    partido: "MOBILIZA",
    numero: "33010",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GERALDINHO ESCOTEIRO",
    partido: "PODE",
    numero: "20651",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GERALDO FILHO DO BARRAOZINHO",
    partido: "MDB",
    numero: "15015",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GERCINO DO TÁXI",
    partido: "PT",
    numero: "13400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GETULIO DA NUTRISETE",
    partido: "PDT",
    numero: "12777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GILBER MARQUES BERA DO NENÉM",
    partido: "AVANTE",
    numero: "70223",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GILBERTO DOCEIRO",
    partido: "REPUBLICANOS",
    numero: "10778",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GILBERTO PINTOR",
    partido: "UNIÃO",
    numero: "44113",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GILSON LIBOREIRO",
    partido: "SOLIDARIEDADE",
    numero: "77000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GISLENE DO ESPERANÇA LENA",
    partido: "REDE",
    numero: "18555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GLEICIENE TEIXEIRA",
    partido: "MDB",
    numero: "15357",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GLEYSSON BARBOSA",
    partido: "PL",
    numero: "22777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GUILTON MOURA DA SAUDE",
    partido: "NOVO",
    numero: "30600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "GUSTAVO CAÇA E PESCA",
    partido: "PL",
    numero: "22017",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "HEIDER MARCELO",
    partido: "PRD",
    numero: "25123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "HELOÍSA FROIS",
    partido: "NOVO",
    numero: "30300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "HIGOR CATATAU",
    partido: "PODE",
    numero: "20200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IGOR FABI",
    partido: "PRD",
    numero: "25252",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IGOR FERNANDO",
    partido: "MDB",
    numero: "15123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "INA LÚCIA",
    partido: "NOVO",
    numero: "30500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ISAÍAS DA AMBULÂNCIA",
    partido: "CIDADANIA",
    numero: "23700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ISMAEL SOARES",
    partido: "PSB",
    numero: "40333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IVAN DO SALÃO",
    partido: "PP",
    numero: "11333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IVAN LUIZ IVANZINHO",
    partido: "PDT",
    numero: "12012",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IVONE OLIVEIRA",
    partido: "MDB",
    numero: "15666",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "IVSON",
    partido: "PL",
    numero: "22222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JANAINA RIBEIRO",
    partido: "PDT",
    numero: "12555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JANAINA RICZ",
    partido: "NOVO",
    numero: "30033",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JANAYNA DIRETORA",
    partido: "MOBILIZA",
    numero: "33444",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JANDERSON AVELAR",
    partido: "MDB",
    numero: "15116",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JANIA RIBEIRO",
    partido: "PP",
    numero: "11190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JAQUELINE COELHO",
    partido: "PODE",
    numero: "20333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JHONY ANTHONY",
    partido: "UNIÃO",
    numero: "44022",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JOÃO BATISTA INVESTIGADOR",
    partido: "REPUBLICANOS",
    numero: "10294",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JOÃO EVANGELISTA",
    partido: "MOBILIZA",
    numero: "33123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JOÃO ROQUE",
    partido: "PSB",
    numero: "40123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JONATAN DO ESCOLAR",
    partido: "PRD",
    numero: "25411",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JOSE MAURÍCIO PARAFUSO",
    partido: "AVANTE",
    numero: "70333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JOVEM DELI",
    partido: "PDT",
    numero: "12007",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JUAREZ NERI",
    partido: "CIDADANIA",
    numero: "23023",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JUCA SETE CORDAS",
    partido: "REDE",
    numero: "18300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JULIANO FISIOTERAPEUTA",
    partido: "PSB",
    numero: "40444",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "JÚLIO GUERREIRO",
    partido: "PRD",
    numero: "25777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "JUSSARA PIRES",
    partido: "MDB",
    numero: "15330",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "KARLA PATRICIA",
    partido: "CIDADANIA",
    numero: "23900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "KÊNIA LESSA",
    partido: "PSB",
    numero: "40400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LATRÉIA",
    partido: "UNIÃO",
    numero: "44118",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LEÔNCIO LOPES",
    partido: "MOBILIZA",
    numero: "33333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LEOZINHO PRODUÇÕES",
    partido: "REDE",
    numero: "18222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LEY SANTOS",
    partido: "PODE",
    numero: "20800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LITON",
    partido: "PP",
    numero: "11321",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUCAS LIMA",
    partido: "MOBILIZA",
    numero: "33456",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUCIANO CAMINHONEIRO",
    partido: "PSB",
    numero: "40113",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUIS FERNANDO",
    partido: "MDB",
    numero: "15777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUIZ DO RESTAURANTE VOVÓ ANITA",
    partido: "PL",
    numero: "22111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUIZ GUSTAVO PRADO",
    partido: "UNIÃO",
    numero: "44400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LUIZINHO ABACAXI",
    partido: "PDT",
    numero: "12600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "LURDINHA TURISMO",
    partido: "REDE",
    numero: "18300",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "MAGELA LANCHES",
    partido: "PP",
    numero: "11600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MAJOR FREITAS",
    partido: "PL",
    numero: "22190",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "MARCÃO PADEIRO",
    partido: "AGIR",
    numero: "36000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCELA FIGUEIREDO",
    partido: "PL",
    numero: "22336",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCELÃO",
    partido: "PODE",
    numero: "20020",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCELINHA ACS",
    partido: "MOBILIZA",
    numero: "33113",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCELO COOPERSELTA DO MEXA-SE",
    partido: "MOBILIZA",
    numero: "33777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCIANA GONZAGA",
    partido: "PODE",
    numero: "20600",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MÁRCIO PAULINO LULU",
    partido: "SOLIDARIEDADE",
    numero: "77800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCOS ANTONIO NEGÃO",
    partido: "UNIÃO",
    numero: "44314",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARCUS IRENO",
    partido: "NOVO",
    numero: "30000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARIA AMELIA PSICÓLOGA",
    partido: "NOVO",
    numero: "30789",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARIA DO SANTO ANTONIO",
    partido: "REPUBLICANOS",
    numero: "10987",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARIA GERALDA DA SOPA",
    partido: "MOBILIZA",
    numero: "33133",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARIA VIANA",
    partido: "CIDADANIA",
    numero: "23200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARIELE VERDOLIN",
    partido: "PL",
    numero: "22560",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARLI DE LUQUINHA",
    partido: "PP",
    numero: "11000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARQUIM SANGÃO",
    partido: "CIDADANIA",
    numero: "23500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MARTA SUAR",
    partido: "PL",
    numero: "22077",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MATEUS MARTINS",
    partido: "PODE",
    numero: "20000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MATHEUS MENDES",
    partido: "PDT",
    numero: "12800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MATHEUS NASCIMENTO",
    partido: "PRD",
    numero: "25250",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MATHEUS ROCHA BITOCA",
    partido: "PODE",
    numero: "20789",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MAURO DO ESPORTE E DA FEIRINHA",
    partido: "PC do B",
    numero: "65000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MEIRE DA SAÚDE",
    partido: "REPUBLICANOS",
    numero: "10222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MICHAEL BRAGA",
    partido: "REPUBLICANOS",
    numero: "10437",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MICHELLE DURÃES",
    partido: "PL",
    numero: "22221",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MILTON MARTINS EVANGELIZE",
    partido: "REPUBLICANOS",
    numero: "10123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MILTON SARAIVA",
    partido: "PSB",
    numero: "40789",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MISS ROSEMEIRE ROSE DA OCUPACA",
    partido: "MDB",
    numero: "15106",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MONICA DO CANADA",
    partido: "PDT",
    numero: "12112",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MONSTRINHO",
    partido: "PP",
    numero: "11100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "MURILO PAIVA",
    partido: "PODE",
    numero: "20125",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NAIARA ABREU",
    partido: "NOVO",
    numero: "30123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NANNA ANDRADE",
    partido: "REDE",
    numero: "18050",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NATAN FARIAS",
    partido: "REDE",
    numero: "18456",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NEGO DO CHURRASQUINHO",
    partido: "PSB",
    numero: "40222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NEUTON OLIVEIRA DA RADIO",
    partido: "PSB",
    numero: "40921",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NILZA BARBOSA",
    partido: "MDB",
    numero: "15138",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NINA LUCAS DA ASPA SETE",
    partido: "PDT",
    numero: "12350",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "NORMA DO CALDO DA FEIRINHA",
    partido: "AVANTE",
    numero: "70222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PABLO DO FACEBURG",
    partido: "CIDADANIA",
    numero: "23103",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR ALCIDES",
    partido: "REPUBLICANOS",
    numero: "10000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR GEOVANE",
    partido: "MOBILIZA",
    numero: "33126",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR JOSÉ MACHADO",
    partido: "AVANTE",
    numero: "70200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR LUIS CLAUDIO",
    partido: "PP",
    numero: "11300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR MAURO DO AMA",
    partido: "MOBILIZA",
    numero: "33111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PASTOR RAMON",
    partido: "REPUBLICANOS",
    numero: "10500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PATRICIA",
    partido: "MOBILIZA",
    numero: "33555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PAULINHO",
    partido: "SOLIDARIEDADE",
    numero: "77200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PAULINHO CIDADÃO SETE",
    partido: "CIDADANIA",
    numero: "23777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PAULO DO BAR",
    partido: "AVANTE",
    numero: "70700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PAULO SOUZA",
    partido: "PRD",
    numero: "25222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PEIXEIRO",
    partido: "SOLIDARIEDADE",
    numero: "77707",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PEREIRA TURR",
    partido: "SOLIDARIEDADE",
    numero: "77322",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PÓ ROYAL",
    partido: "MDB",
    numero: "15678",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "POLICIAL DIAS",
    partido: "MOBILIZA",
    numero: "33040",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PRETO SERRALHEIRO",
    partido: "PSB",
    numero: "40200",
    situacao: "Inapto",
    tags: "vereador",
},
{
    candidato: "PROFESSOR ALEXANDRE",
    partido: "REDE",
    numero: "18777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PROFESSOR DENIS",
    partido: "PDT",
    numero: "12999",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PROFESSOR FARLEY",
    partido: "PDT",
    numero: "12345",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PROFESSORA FÂNIA MARQUES",
    partido: "SOLIDARIEDADE",
    numero: "77777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PROFESSORA RAILDA",
    partido: "PRD",
    numero: "25888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "PRYSCILLA SOUZA",
    partido: "PRD",
    numero: "25321",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RAFAEL FAISCA",
    partido: "AVANTE",
    numero: "70800",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RALPH MACHADO",
    partido: "PL",
    numero: "22500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RAMSÉS DE CASTRO",
    partido: "PT",
    numero: "13000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RANNY REIS CANTORA",
    partido: "AVANTE",
    numero: "70777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RAQUEL GLÓRIA",
    partido: "PODE",
    numero: "20123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "REGINA AGUIAR",
    partido: "CIDADANIA",
    numero: "23100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "REGINALDO TRISTEZA",
    partido: "CIDADANIA",
    numero: "23000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "REINALDO MARTINS",
    partido: "MDB",
    numero: "15033",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "REJANE FÉLIX",
    partido: "PT",
    numero: "13313",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RENATA DO ESPORTE",
    partido: "REDE",
    numero: "18111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RENATO GOMES",
    partido: "MDB",
    numero: "15333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RODRIGO BRAGA",
    partido: "MDB",
    numero: "15555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RODRIGO MOSQUITINHO",
    partido: "REDE",
    numero: "18200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ROGERIO DA ESCOLINHA VASQUINHO",
    partido: "PRD",
    numero: "25678",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ROGÉRIO MARTINS",
    partido: "PT",
    numero: "13777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RONALDINHO DA BICICLETA",
    partido: "PSB",
    numero: "40500",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RONEY DO APROXIMAR",
    partido: "PP",
    numero: "11777",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RONILDO",
    partido: "REPUBLICANOS",
    numero: "10001",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ROSANA RIBEIRO",
    partido: "NOVO",
    numero: "30330",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "RUTINHA DO PCDOB",
    partido: "PC do B",
    numero: "65555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SÂMARA RESENDE",
    partido: "PP",
    numero: "11767",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SERGINHO NA VEIA",
    partido: "MDB",
    numero: "15900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SÉRGIO FILHO DE LUIZ MÃOZINHA",
    partido: "SOLIDARIEDADE",
    numero: "77444",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SERGIO SHELL",
    partido: "PP",
    numero: "11900",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SGT MIRANDA",
    partido: "UNIÃO",
    numero: "44190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SIDÃO",
    partido: "MOBILIZA",
    numero: "33033",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SILVIA REGINA",
    partido: "REDE",
    numero: "18100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SILVIO SANTOS",
    partido: "REDE",
    numero: "18121",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SIMONE AVELAR",
    partido: "PODE",
    numero: "20100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SIMONE DA POINT CAR",
    partido: "SOLIDARIEDADE",
    numero: "77733",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SONIA MACHADO",
    partido: "MOBILIZA",
    numero: "33190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SUBTENENTE DAWISON",
    partido: "PODE",
    numero: "20193",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "SUPER BELLA",
    partido: "PDT",
    numero: "12888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TAMIRES AGENCIA DA SAUDE",
    partido: "PP",
    numero: "11999",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TARABAL",
    partido: "SOLIDARIEDADE",
    numero: "77007",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TATIANA VIANNA",
    partido: "PRD",
    numero: "25114",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TEKÃO DO PÃO",
    partido: "SOLIDARIEDADE",
    numero: "77700",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TEO DA EQUOTERAPIA SGT GONZALE",
    partido: "PODE",
    numero: "20244",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TEREZA",
    partido: "CIDADANIA",
    numero: "23005",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "THIAGO SANTANA",
    partido: "REPUBLICANOS",
    numero: "10100",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TIA LEO DO ESCOLAR",
    partido: "PSB",
    numero: "40888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TIM DO BAR",
    partido: "PC do B",
    numero: "65400",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "TIO MIRO",
    partido: "PP",
    numero: "11200",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "VAMBERTO TEIXEIRA DA MUSIRAMA",
    partido: "SOLIDARIEDADE",
    numero: "77111",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "VANIA BATISTA LÔRA",
    partido: "SOLIDARIEDADE",
    numero: "77222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "VINI REPRESENTAÇÕES",
    partido: "PL",
    numero: "22555",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WAGUINHO DE CARMELITA",
    partido: "NOVO",
    numero: "30333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WALISSON LELÉ DO VERDE VALE",
    partido: "REDE",
    numero: "18888",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WANDERLEY AROEIRA",
    partido: "SOLIDARIEDADE",
    numero: "77123",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WANDERLEY GAMA BOCA",
    partido: "MDB",
    numero: "15190",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WANDERSON PACHA",
    partido: "PRD",
    numero: "25333",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WARLEY ALCANTÂRA",
    partido: "NOVO",
    numero: "30007",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WARLEY DO SALÃO",
    partido: "PODE",
    numero: "20300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WARLEY SOARES",
    partido: "PRD",
    numero: "25966",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WILLIAN SILVA",
    partido: "PODE",
    numero: "20222",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WILSON ROCHA",
    partido: "MDB",
    numero: "15300",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "WINICIUS RAPOSO",
    partido: "PL",
    numero: "22000",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ZÉ ANTÔNIO SALÃO",
    partido: "AVANTE",
    numero: "70570",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ZE GOMES DA MERCEARIA",
    partido: "PDT",
    numero: "12607",
    situacao: "Concorrendo",
    tags: "vereador",
},
{
    candidato: "ZEZÉ PANFLETOS",
    partido: "PL",
    numero: "22140",
    situacao: "Concorrendo",
    tags: "vereador",
},



    
    

];


